# Basic pre-commit configuration for Glance
# This file defines the structure for pre-commit hooks

repos:
  # Standard file formatting hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Basic file formatting hooks will be added here in T007
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Go-specific hooks
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      # Go formatting hooks
      - id: go-fmt
        name: go fmt
        description: Run gofmt on files
        language: system
        pass_filenames: true
        files: \.go$
      - id: go-imports
        name: go imports
        description: Run goimports on files
        language: system
        pass_filenames: true
        files: \.go$
        args: ["-w", "-local", "github.com/phrazzld/glance"]
      
      # Go code analysis hooks
      - id: go-vet
        name: go vet
        description: Run go vet on packages to analyze code for suspicious constructs
        language: system
        pass_filenames: false
        files: \.go$
        args: ["./..."]
        verbose: true
        
      # Go linting hooks from dnephin repo
      - id: golangci-lint
        name: go-repo linter
        description: Run golangci-lint through the pre-commit-golang repo
        args: ["--config=.golangci.yml", "--new-from-rev=HEAD~1"]

  # Linting hooks
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.0
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: Fast Go linters runner that uses .golangci.yml config
        language: system
        entry: golangci-lint run
        types: [go]
        pass_filenames: false
        args: ["--fix", "--timeout=5m"]
        verbose: true

  # Security-focused hooks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      # Placeholder for security hooks
      - id: detect-secrets