# Basic pre-commit configuration for Glance
# This file defines the structure for pre-commit hooks

repos:
  # Standard file formatting hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Basic file formatting hooks will be added here in T007
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # Go-specific hooks
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      # Go formatting hooks
      - id: go-fmt
        name: go fmt
        description: Run gofmt on files
        language: system
        pass_filenames: true
        files: \.go$
      - id: go-imports
        name: go imports
        description: Run goimports on files
        language: system
        pass_filenames: true
        files: \.go$
        args: ["-w", "-local", "github.com/phrazzld/glance"]

  # Security-focused hooks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      # Placeholder for security hooks
      - id: detect-secrets